name: Update README

on:
    schedule:
        - cron: '0 * * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Run README build
            run: echo "README updated on $(date)" > README.md
        - name: Push changes
            uses: ad-m/github-push-action@master
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}